spring:
  application:
    name: demo-orders
server:
  port: 8650
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
---
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/demo-store;AUTO_SERVER=TRUE
    username: sa
    password:
    driverClassName: org.h2.Driver